# Generated by Django 5.2.16 on 2026-08-13 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name_plural': 'participants',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.participant')),
            ],
            options={
                'verbose_name_plural': 'enrollments',
                'ordering': ('activity', 'participant'),
                'unique_together': {('activity', 'participant')},
            },
        ),
    ]
